---
- hosts: all

  tasks:
  - name: copy foo.txt blank file into OCC dir
    copy:
     src: /opt/offline_provisioner/ansible/files/foo.txt
     dest: /root/.
     owner: root
     group: root
     mode: '0770'

